service: locaria-rds
projectDir: ../../../
provider:
  name: aws
  profile: ${file(../../../locaria.json):${self:custom.stage}.profile}
  runtime: nodejs14.x
  region: ${file(../../../locaria.json):${self:custom.stage}.region}


custom:
  stage: "${opt:stage, self:provider.stage}"

resources:
  Resources:
    AuroraLambdaRole:
      Type: "AWS::IAM::Role"
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - rds.amazonaws.com
              Action:
                - "sts:AssumeRole"
        Policies:
          - PolicyName: root
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action: "lambda:InvokeFunction"
                  Resource: '*'
        Path: "/"
    AuroraStorageSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Ingress for Aurora
        VpcId: ${file(../outputs/${self:custom.stage}-outputs.json):vpcId}
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: ${file(../../../locaria.json):${self:custom.stage}.DBPort}
            ToPort: ${file(../../../locaria.json):${self:custom.stage}.DBPort}
            CidrIp: 10.0.0.0/16
          - IpProtocol: tcp
            FromPort: ${file(../../../locaria.json):${self:custom.stage}.DBPort}
            ToPort: ${file(../../../locaria.json):${self:custom.stage}.DBPort}
            CidrIp: ${file(../../../locaria.json):${self:custom.stage}.VPNCDR}
    AuroraSubnetGroup:
      Type: AWS::RDS::DBSubnetGroup
      Properties:
        DBSubnetGroupDescription: "Aurora Subnet Group"
        SubnetIds:
          - ${file(../outputs/${self:custom.stage}-outputs.json):vpcPrivateSubnetA}
          - ${file(../outputs/${self:custom.stage}-outputs.json):vpcPrivateSubnetB}
    AuroraRDSInstanceParameter:
      Type: AWS::RDS::DBParameterGroup
      Properties:
        Description: Parameter group for the Serverless Aurora RDS DB.
        Family: ${file(../../../locaria.json):${self:custom.stage}.auroraFamily}
        Parameters:
          max_connections: 5000
          shared_preload_libraries: pg_cron
    RDSInstance:
      Type: "AWS::RDS::DBInstance"
      Properties:
        DBSubnetGroupName:
          Ref: AuroraSubnetGroup
        Engine: postgres
        EngineVersion: ${file(../../../locaria.json):${self:custom.stage}.auroraVersion}
        DBInstanceClass: ${file(../../../locaria.json):${self:custom.stage}.DBInstanceClass}
        PubliclyAccessible: ${file(../../../locaria.json):${self:custom.stage}.DBPubliclyAccessible}
        MasterUsername: ${file(../../../locaria.json):${self:custom.stage}.auroraMasterUser}
        MasterUserPassword: ${file(../../../locaria.json):${self:custom.stage}.auroraMasterPass}
        DBName: locariamain
        BackupRetentionPeriod: 3
        VPCSecurityGroups:
          - Ref: AuroraStorageSecurityGroup
        AssociatedRoles:
          - FeatureName: Lambda
            RoleArn: !GetAtt [ AuroraLambdaRole, Arn ]
        AllocatedStorage: 50
        Port: ${file(../../../locaria.json):${self:custom.stage}.DBPort}
        DBParameterGroupName:
          Ref: AuroraRDSInstanceParameter
plugins:
  - serverless-stack-output